### PR TITLE
Base implementation of Markdown lexical analyzer

### PR DESCRIPTION
**Pull request by martintc**
Markdown lexical analyzer takes in a markdown file and creates a stream of tokens. This is still a working branch, but wanted to move some work into dev, then into main. Also included is an initial implementation of a github actions file to allow for running go unit tests upon each commit, push, and PR. This will improve code quality and display that functionality is passing tests. 

This branch will still be worked on as the converters from markdown tokens to HTML and Gemtext files needs to be implemented

In order to run tests, pull down branch and navigate to the ianus folder. Then run
`go test -v ./...`

@kraileth looking for your input before merging into dev. If you approve, I will go ahead and merge it into main without approval.

### CODE REVIEW

**Review by kraileth — CHANGES_REQUESTED** [review]
Ran the tests on FreeBSD 13.0 and they all passed. Only thing that I noticed was that you accidentally committed and pushed the compiled binary. You may definitely want to remove that before merging (and probably add `ianus/ianus` to `.gitignore`?).

Couldn't figure out how to comment specifically on a binary file, so I'm including this here.

**Comment by martintc** [comment]
> Ran the tests on FreeBSD 13.0 and they all passed. Only thing that I noticed was that you accidentally committed and pushed the compiled binary. You may definitely want to remove that before merging (and probably add `ianus/ianus` to `.gitignore`?).
> 
> 
> 
> Couldn't figure out how to comment specifically on a binary file, so I'm including this here.

Good catch, I'll remove it tonight. Can't believe that escaped me, I'm usually pretty good at filling out gitignore or just paying attention to the status of files in magit. Probably escaped me since I have all the source in an ianus folder. Will get it removed tonight and let you review again for approval.

**Comment by martintc** [comment]
> Ran the tests on FreeBSD 13.0 and they all passed. Only thing that I noticed was that you accidentally committed and pushed the compiled binary. You may definitely want to remove that before merging (and probably add `ianus/ianus` to `.gitignore`?).
> 
> Couldn't figure out how to comment specifically on a binary file, so I'm including this here.

Change requested has occured. Deleted the binary file.

**Review by kraileth — APPROVED** [review]
Looks good to me now

**Pull request merged**
